= Reference

== Data type mapping
The type support relies on link:https://neo4j.com/docs/jdbc-manual/current/datatypes/[Neo4j JDBC Driver type support].
There is no special handling for AWS Glue in place.

== Options and configuration
Please refer to the link:https://neo4j.com/docs/jdbc-manual/current/configuration/[Neo4j JDBC Driver documentation] for all the parameters that are supported within the JDBC URL.

== FAQ and troubleshooting
Most problems can be seen already in the visual ETL flow when AWS Glue tries to render the data preview. At least when running a job, the overview will report the stacktrace with the messages below, if a failure occurs.

Here are some common error scenarios and how to solve them.

=== Credentials or URI wrong
The message usually means that there is something wrong with the initial connection to the database.

```
Glue ETL Marketplace:
failed to retrieve table schema from source.driverClassName: org.neo4j.jdbc.Neo4jDriver,
error message: org.neo4j.jdbc.internal.shaded.bolt.exception.BoltServiceUnavailableException:
Unable to connect to <neo4j endpoint>, ensure the database is running and that there is a working network connection to it.
```

This could be either wrong / insufficient credentials or the wrong URI pointing to the instance.
The URI and parameters on the connection page should be checked again and fixed, ensure you have xref:getting-started.adoc#_creating_a_connection[stored the credentials correctly]. 

=== Target schema missing

```
Glue ETL Marketplace: table does not exist.
```

This message indicates that there is no label yet in the database with the target "table name".

```
Glue ETL Marketplace: JDBC Data Sink: Column "" not found in schema Some(...)...
```

Not only the labels have to exist but also the properties on the target nodes. (refer to section Writing to non-existent labels / properties)

